name: scrolling_demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  scroll_page_view: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/google-fonts/
