export const initialProducts = [
	{
		name: 'Laptop',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: '1',
	},
	{
		name: 'Smartphone',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: '2',
	},
	{
		name: 'Coffee Maker',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: '3',
	},
	{
		name: 'Running Shoes',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: '4',
	},
	{
		name: 'Backpack',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: '5',
	},
	{
		name: 'Laptop1',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: '6',
	},
	{
		name: 'Smartphone1',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: '7',
	},
	{
		name: 'Coffee Maker1',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: '8',
	},
	{
		name: 'Running Shoes1',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: '9',
	},
	{
		name: 'Backpack1',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: '10',
	},
	{
		name: 'Laptop2',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: '11',
	},
	{
		name: 'Smartphone2',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: '12',
	},
	{
		name: 'Coffee Maker2',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: '13',
	},
	{
		name: 'Running Shoes2',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: '14',
	},
	{
		name: 'Backpack2',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: '15',
	},
	{
		name: 'Laptop3',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: '16',
	},
	{
		name: 'Smartphone3',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: '17',
	},
	{
		name: 'Coffee Maker3',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: '18',
	},
	{
		name: 'Running Shoes3',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: '19',
	},
	{
		name: 'Backpack3',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: '20',
	},
];

export const initialOrders = [
	{
		id: '1',
		customerName: 'John Doe',
		orderDate: 1699964400,
		status: 'Pending',
		items: [
			{
				id: 101,
				name: 'Widget A',
				quantity: 2,
				price: 10,
			},
			{
				id: 102,
				name: 'Widget B',
				quantity: 1,
				price: 15,
			},
		],
		shippingAddress: {
			street: '123 Main St',
			city: 'Anytown',
			state: 'CA',
			postalCode: '12345',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 35,
		estimatedDeliveryDate: 1700050800,
	},
	{
		id: '2',
		customerName: 'Jane Smith',
		orderDate: 1699878000,
		status: 'Shipped',
		items: [
			{
				id: 103,
				name: 'Widget C',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '456 Oak St',
			city: 'Sometown',
			state: 'NY',
			postalCode: '54321',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1700050800,
	},
	{
		id: '3',
		customerName: 'Alice Johnson',
		orderDate: 1699791600,
		status: 'Delivered',
		items: [
			{
				id: 104,
				name: 'Widget D',
				quantity: 1,
				price: 25,
			},
			{
				id: 105,
				name: 'Widget E',
				quantity: 2,
				price: 30,
			},
		],
		shippingAddress: {
			street: '789 Elm St',
			city: 'Othertown',
			state: 'TX',
			postalCode: '67890',
		},
		paymentMethod: 'Bank Transfer',
		totalPrice: 85,
		estimatedDeliveryDate: 1700050800,
	},
	{
		id: '4',
		customerName: 'Bob Brown',
		orderDate: 1699705200,
		status: 'Pending',
		items: [
			{
				id: 106,
				name: 'Widget F',
				quantity: 2,
				price: 15,
			},
		],
		shippingAddress: {
			street: '321 Pine St',
			city: 'Somewhere',
			state: 'FL',
			postalCode: '54321',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 30,
		estimatedDeliveryDate: 1699878000,
	},
	{
		id: '5',
		customerName: 'Emily Davis',
		orderDate: 1699618800,
		status: 'Shipped',
		items: [
			{
				id: 107,
				name: 'Widget G',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '654 Birch St',
			city: 'Another Town',
			state: 'WA',
			postalCode: '45678',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1699791600,
	},
	{
		id: '6',
		customerName: 'David Wilson',
		orderDate: 1699532400,
		status: 'Delivered',
		items: [
			{
				id: 108,
				name: 'Widget H',
				quantity: 1,
				price: 25,
			},
		],
		shippingAddress: {
			street: '987 Cedar St',
			city: 'Smalltown',
			state: 'GA',
			postalCode: '34567',
		},
		paymentMethod: 'Bank Transfer',
		totalPrice: 25,
		estimatedDeliveryDate: 1699705200,
	},
	{
		id: '7',
		customerName: 'Sarah Garcia',
		orderDate: 1699446000,
		status: 'Pending',
		items: [
			{
				id: 109,
				name: 'Widget I',
				quantity: 2,
				price: 15,
			},
			{
				id: 110,
				name: 'Widget J',
				quantity: 1,
				price: 10,
			},
		],
		shippingAddress: {
			street: '789 Maple St',
			city: 'Villagetown',
			state: 'NC',
			postalCode: '23456',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 40,
		estimatedDeliveryDate: 1699618800,
	},
	{
		id: '8',
		customerName: 'Michael Martinez',
		orderDate: 1699359600,
		status: 'Shipped',
		items: [
			{
				id: 111,
				name: 'Widget K',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '321 Oak St',
			city: 'Foresttown',
			state: 'OR',
			postalCode: '34567',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1699532400,
	},
	{
		id: '9',
		customerName: 'Jennifer Taylor',
		orderDate: 1699273200,
		status: 'Delivered',
		items: [
			{
				id: 112,
				name: 'Widget L',
				quantity: 1,
				price: 25,
			},
			{
				id: 113,
				name: 'Widget M',
				quantity: 2,
				price: 30,
			},
		],
		shippingAddress: {
			street: '456 Pine St',
			city: 'Mountain Town',
			state: 'CO',
			postalCode: '45678',
		},
		paymentMethod: 'Bank Transfer',
		totalPrice: 85,
		estimatedDeliveryDate: 1699446000,
	},
	{
		id: '10',
		customerName: 'Daniel Brown',
		orderDate: 1699186800,
		status: 'Pending',
		items: [
			{
				id: 114,
				name: 'Widget N',
				quantity: 2,
				price: 15,
			},
		],
		shippingAddress: {
			street: '123 Oak St',
			city: 'Smalltown',
			state: 'AL',
			postalCode: '23456',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 30,
		estimatedDeliveryDate: 1699359600,
	},
	{
		id: '11',
		customerName: 'Jessica Clark',
		orderDate: 1699100400,
		status: 'Shipped',
		items: [
			{
				id: 115,
				name: 'Widget O',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '789 Elm St',
			city: 'Villagetown',
			state: 'DE',
			postalCode: '34567',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1699273200,
	},
	{
		id: '12',
		customerName: 'Andrew White',
		orderDate: 1699014000,
		status: 'Delivered',
		items: [
			{
				id: 116,
				name: 'Widget P',
				quantity: 1,
				price: 25,
			},
		],
		shippingAddress: {
			street: '654 Maple St',
			city: 'Foresttown',
			state: 'FL',
			postalCode: '45678',
		},
		paymentMethod: 'Bank Transfer',
		totalPrice: 25,
		estimatedDeliveryDate: 1699186800,
	},
	{
		id: '13',
		customerName: 'David Thomas',
		orderDate: 1698927600,
		status: 'Pending',
		items: [
			{
				id: 117,
				name: 'Widget Q',
				quantity: 2,
				price: 15,
			},
			{
				id: 118,
				name: 'Widget R',
				quantity: 1,
				price: 10,
			},
		],
		shippingAddress: {
			street: '123 Birch St',
			city: 'Othertown',
			state: 'IL',
			postalCode: '23456',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 40,
		estimatedDeliveryDate: 1699100400,
	},
	{
		id: '14',
		customerName: 'Megan Rodriguez',
		orderDate: 1698841200,
		status: 'Shipped',
		items: [
			{
				id: 119,
				name: 'Widget S',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '456 Cedar St',
			city: 'Smalltown',
			state: 'IA',
			postalCode: '34567',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1699014000,
	},
	{
		id: '15',
		customerName: 'Nicole Walker',
		orderDate: 1698754800,
		status: 'Delivered',
		items: [
			{
				id: 120,
				name: 'Widget T',
				quantity: 1,
				price: 25,
			},
			{
				id: 121,
				name: 'Widget U',
				quantity: 2,
				price: 30,
			},
		],
		shippingAddress: {
			street: '789 Oak St',
			city: 'Mountain Town',
			state: 'KS',
			postalCode: '45678',
		},
		paymentMethod: 'Bank Transfer',
		totalPrice: 85,
		estimatedDeliveryDate: 1698927600,
	},
	{
		id: '16',
		customerName: 'Matthew Scott',
		orderDate: 1698668400,
		status: 'Pending',
		items: [
			{
				id: 122,
				name: 'Widget V',
				quantity: 2,
				price: 15,
			},
		],
		shippingAddress: {
			street: '123 Elm St',
			city: 'Bigtown',
			state: 'MA',
			postalCode: '23456',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 30,
		estimatedDeliveryDate: 1698841200,
	},
	{
		id: '17',
		customerName: 'Lauren King',
		orderDate: 1698582000,
		status: 'Shipped',
		items: [
			{
				id: 123,
				name: 'Widget W',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '456 Maple St',
			city: 'Forestown',
			state: 'ME',
			postalCode: '34567',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1698754800,
	},
	{
		id: '18',
		customerName: 'Brian Adams',
		orderDate: 1698495600,
		status: 'Delivered',
		items: [
			{
				id: 124,
				name: 'Widget X',
				quantity: 1,
				price: 25,
			},
		],
		shippingAddress: {
			street: '654 Cedar St',
			city: 'Smalltown',
			state: 'MD',
			postalCode: '45678',
		},
		paymentMethod: 'Bank Transfer',
		totalPrice: 25,
		estimatedDeliveryDate: 1698668400,
	},
	{
		id: '19',
		customerName: 'Christopher Hill',
		orderDate: 1698409200,
		status: 'Pending',
		items: [
			{
				id: 125,
				name: 'Widget Y',
				quantity: 2,
				price: 15,
			},
			{
				id: 126,
				name: 'Widget Z',
				quantity: 1,
				price: 10,
			},
		],
		shippingAddress: {
			street: '123 Cedar St',
			city: 'Othertown',
			state: 'WA',
			postalCode: '23456',
		},
		paymentMethod: 'Credit Card',
		totalPrice: 40,
		estimatedDeliveryDate: 1698582000,
	},
	{
		id: '20',
		customerName: 'Amanda Lee',
		orderDate: 1698322800,
		status: 'Shipped',
		items: [
			{
				id: 127,
				name: 'Widget AA',
				quantity: 3,
				price: 20,
			},
		],
		shippingAddress: {
			street: '456 Elm St',
			city: 'Bigtown',
			state: 'FL',
			postalCode: '34567',
		},
		paymentMethod: 'PayPal',
		totalPrice: 60,
		estimatedDeliveryDate: 1698495600,
	},
];
