export const initialProducts = [
	{
		name: 'Laptop',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: 1,
	},
	{
		name: 'Smartphone',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: 2,
	},
	{
		name: 'Coffee Maker',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: 3,
	},
	{
		name: 'Running Shoes',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: 4,
	},
	{
		name: 'Backpack',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: 5,
	},
	{
		name: 'Laptop1',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: 6,
	},
	{
		name: 'Smartphone1',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: 7,
	},
	{
		name: 'Coffee Maker1',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: 8,
	},
	{
		name: 'Running Shoes1',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: 9,
	},
	{
		name: 'Backpack1',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: 10,
	},
	{
		name: 'Laptop2',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: 11,
	},
	{
		name: 'Smartphone2',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: 12,
	},
	{
		name: 'Coffee Maker2',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: 13,
	},
	{
		name: 'Running Shoes2',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: 14,
	},
	{
		name: 'Backpack2',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: 15,
	},
	{
		name: 'Laptop3',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
		id: 16,
	},
	{
		name: 'Smartphone3',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
		id: 17,
	},
	{
		name: 'Coffee Maker3',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
		id: 18,
	},
	{
		name: 'Running Shoes3',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
		id: 19,
	},
	{
		name: 'Backpack3',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
		id: 20,
	},
];
