export const initialProducts = [
	{
		name: 'Laptop',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
	},
	{
		name: 'Smartphone',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
	},
	{
		name: 'Coffee Maker',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
	},
	{
		name: 'Running Shoes',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
	},
	{
		name: 'Backpack',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
	},
	{
		name: 'Laptop1',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
	},
	{
		name: 'Smartphone1',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
	},
	{
		name: 'Coffee Maker1',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
	},
	{
		name: 'Running Shoes1',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
	},
	{
		name: 'Backpack1',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
	},
	{
		name: 'Laptop2',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
	},
	{
		name: 'Smartphone2',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
	},
	{
		name: 'Coffee Maker2',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
	},
	{
		name: 'Running Shoes2',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
	},
	{
		name: 'Backpack2',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
	},
	{
		name: 'Laptop3',
		category: 'Electronics',
		price: 999.99,
		stockQuantity: 50,
	},
	{
		name: 'Smartphone3',
		category: 'Electronics',
		price: 599.99,
		stockQuantity: 100,
	},
	{
		name: 'Coffee Maker3',
		category: 'Appliances',
		price: 49.99,
		stockQuantity: 30,
	},
	{
		name: 'Running Shoes3',
		category: 'Clothing',
		price: 79.99,
		stockQuantity: 75,
	},
	{
		name: 'Backpack3',
		category: 'Accessories',
		price: 39.99,
		stockQuantity: 50,
	},
];
